<?php
// clovek.inc

$domain_kontakt_viditelnost = array(
	0=>$lang['public'],
	1=>$lang['registered'],
	2=>$lang['club only']
);

$domain_kontakt_druh = array(
	'telefon'=>$lang['phone'],
	'email'=>$lang['email'],
	'adresa'=>$lang['postal'],
	'icq'=>$lang['icq'],
	'jabber'=>$lang['jabber'],
	'web'=> $lang['web']
);

$domain_prava_souteze = array(
	0=>$lang['access competitions0'],
	1=>$lang['access competitions1'],
	2=>$lang['access competitions2']
);

$domain_prava_lidi = array(
	0=>$lang['access people0'],
	1=>$lang['access people1'],
	2=>$lang['access people2'],
	3=>$lang['access people3']
);

$domain_prava_kluby = array(
	0=>$lang['access clubs0'],
	1=>$lang['access clubs1'],
	2=>$lang['access clubs2']
);

$domain_prava_souteze = array(
	0=>$lang['access competitions0'],
	1=>$lang['access competitions1'],
	2=>$lang['access competitions2']
);

$domain_prava_debaty = array(
	0=>$lang['access debates0'],
	1=>$lang['access debates1']
);

// fetch the person

// basic details

// club positions (coach)

// accreditations

// contacts

// login

// teams

// tournaments (org)

// points overview

// debates
?>
