<?php

global $domain_klub_role;
$domain_klub_role = array(
	"t"=>$lang["coach"]
);

global $domain_turnaj_role;
$domain_turnaj_role = array(
	"o"=>$lang["organizer"]
);

global $domain_debata_role;
$domain_debata_role = array(
	"r"=>$lang["adjudicator"],
	"o"=>$lang["organizer"],
	"a1"=>$lang["A1"],
	"a2"=>$lang["A2"],
	"a3"=>$lang["A3"],
	"n1"=>$lang["N1"],
	"n2"=>$lang["N2"],
	"n3"=>$lang["N3"]
);

global $domain_ibody_role;
$domain_ibody_role = array(
	"debater"=>$lang["debater"],
	"rozhodci"=>$lang["adjudicator"],
	"trener"=>$lang["coach"],
	"organizator"=>$lang["organizer"]
);

global $domain_kontakt_viditelnost;
$domain_kontakt_viditelnost = array(
	0=>$lang['public'],
	1=>$lang['registered'],
	2=>$lang['club only']
);

global $domain_kontakt_druh;
$domain_kontakt_druh = array(
	'telefon'=>$lang['phone'],
	'email'=>$lang['email'],
	'adresa'=>$lang['postal'],
	'icq'=>$lang['icq'],
	'jabber'=>$lang['jabber'],
	'web'=> $lang['web']
);

global $domain_prava_souteze;
$domain_prava_souteze = array(
	0=>$lang['access competitions0'],
	1=>$lang['access competitions1'],
	2=>$lang['access competitions2']
);

global $domain_prava_lidi;
$domain_prava_lidi = array(
	0=>$lang['access people0'],
	1=>$lang['access people1'],
	2=>$lang['access people2'],
	3=>$lang['access people3']
);

global $domain_prava_kluby;
$domain_prava_kluby = array(
	0=>$lang['access clubs0'],
	1=>$lang['access clubs1'],
	2=>$lang['access clubs2']
);

global $domain_prava_souteze;
$domain_prava_souteze = array(
	0=>$lang['access competitions0'],
	1=>$lang['access competitions1'],
	2=>$lang['access competitions2']
);

$domain_prava_debaty = array(
	0=>$lang['access debates0'],
	1=>$lang['access debates1']
);

?>