set foreign_key_checks = 0;
drop table clovek_debata_ibody;
drop table clovek_debata;
drop table liga_tym;
drop table debata_tym;
drop table debata;
drop table clovek_klub;
drop table clovek_turnaj;
drop table clovek_tym;
drop table kontakt;
drop table login;
drop table rozhodci;
drop table clovek;
drop table tym;
drop table klub;
drop table soutez_teze;
drop table turnaj;
drop table liga;
drop table soutez;
drop table teze;
set foreign_key_checks = 1;