<?php

$GLOBALS["cp_config"]["db_server"] = "localhost";
$GLOBALS["cp_config"]["db_database"] = "greybox";
$GLOBALS["cp_config"]["db_user"] = "greybox";
$GLOBALS["cp_config"]["db_password"] = "greybox";

$GLOBALS["cp_config"]["title"] = "greybox";

$GLOBALS["current_season"] = 0; // = 2000/2001
$GLOBALS["season_domain"] = array(
	0=>"2000/2001 (test)",
	3=>"2003/2004",
	4=>"2004/2005",
	5=>"2005/2006"
);

?>
