#!/bin/bash
#
# sync_lang <language file 1> <language file 2>
# adds missing record to both language files
# language files have to end with '?>' line

ex -c '$d' -c 'w' -c 'q' "$1"
ex -c '$d' -c 'w' -c 'q' "$2"

grep -o "^\$lang\['[^']*'" "$1" | cut -c '7-' > /tmp/lang$$_1
grep -o "^\$lang\['[^']*'" "$2" | cut -c '7-' > /tmp/lang$$_2

diff /tmp/lang$$_1 /tmp/lang$$_2 > /tmp/lang$$_3

# add to 2
cat /tmp/lang$$_3 | grep '^< ' | cut -c '3-' | while read line
do
	echo '$lang['$line'] = '$line';' >> "$2"
done

# add to 1
cat /tmp/lang$$_3 | grep '^> ' | cut -c '3-' | while read line
do
	echo '$lang['$line'] = '$line';' >> "$1"
done

echo '?>' >> "$1"
echo '?>' >> "$2"

rm /tmp/lang$$_[123]
